### ISSUE TITLE
Need to Receive MO SMS and set auto reply

### ISSUE THREAD

**Issue by 89viral** [OpenSmpp/opensmpp#10]
Hello, 

i am able to send SMS Successfully. but i am not receiving SMS 

this is my code to receive PDU

 try {
            while (true) {
                try {
                    System.out.println("SMSCSession going to receive a PDU");
                    pdu = session.receive(30000);
                } catch (Exception e) {
                    System.out.println("SMSCSession caught exception receiving PDU " + e.getMessage());
                }
                if (pdu != null) {
                    timeoutCntr = 0;
                    if (pdu.isRequest()) {
                        System.out.println("SMSCSession got request " + pdu.debugString());

```
                } else if (pdu.isResponse()) {
                    System.out.println("SMSCSession got response " + pdu.debugString());

                } else {
                    System.out.println("SMSCSession not reqest nor response => not doing anything.");
                }
            }
        }
```

**Comment by paoloc0** [comment]
If you can dump network traffic, it may help you determine if there is an SMS even being sent to you, for the code to receive. I'm closing this issue because a long time has passed, and this is not likely to be useful so late after the fact.
