### ISSUE TITLE
Indian Local Language Encoding Issue

### ISSUE THREAD

**Issue by tkiran77** [OpenSmpp/opensmpp#15]
Hello,
We have been using opensmpp library for some of our applications for quite some time. We are facing a unique issue, when sending sms in unicode, sms when sent using Hindi or Telugu languages its delivering fine, but when sending using Gujarathi or Tamil the messages are garbled at the end handset.
We tried to analyse the issue and found that, when the message data is being converted to byes using .getBytes("ASCII") the specific language content is getting garbled with either ? or something else. We assume this is a encoding/charset issue, any help in this regard would be appreciated ?
Also has anyone faced or fixed issues in the lib in this regard ?
Do let us know if you need more information to be able to help us with a possible solution.
Thanks

**Comment by tkiran77** [comment]
Hello,
While reviewing the code for the above issue, we found in the following function , code only 7-bit or ASCII encoding is used, there is no use of UTF-8 that we felt could be one of the possible issues, we did try UTF-8 instead of ASCII but the problem persisted:

/**
	 * Sets the message a new value. Default encoding <code>Data.ENC_GSM7BIT</code>
	 * is used.
	 * @param message the message
	 * @exception WrongLengthOfStringException thrown when the message
	 *            too short or long
	 */
	public void setMessage(String message) throws WrongLengthOfStringException {
		try {
			setMessage(message, Data.ENC_GSM7BIT);
		} catch (UnsupportedEncodingException e) {
			try {
				setMessage(message, Data.ENC_ASCII);
			} catch (UnsupportedEncodingException uee) {
				// ascii always supported
			}
		}
	}

Please share your thoughts on the above if instead of ENC_ASCII UTF-8 or UTF-16 needs to be used for getting all language support in the encoding ?
Thanks

**Comment by bodunov** [comment]
Try using dataCoding 0x08 and encoding UTF-16BE. For example:

```
SubmitSM request = new SubmitSM();
request.setShortMessage(message, Data.ENC_UTF16_BE);
request.setDataCoding((byte)0x08);
```
