### ISSUE TITLE
Overflow not detected by GSM7Charset.Gsm7BitEncoder and GSM7Charset.Gsm7BitDecoder

### ISSUE THREAD

**Issue by mikaelcarlstedt** [OpenSmpp/opensmpp#16]
When a character buffer with only basic GSM characters and a byte buffer of insufficient size is provided as argument to Gsm7BitEncoder.encode(), the return value is CoderResult.UNDERFLOW but it should be CoderResult.OVERFLOW. Vice versa, GSM7BitDecoder.decode() returns CoderResult.UNDERFLOW even though a character buffer of insufficient size is provided as argument.

**Comment by ptomli** [comment]
Resolved in #28
