### ISSUE TITLE
Having an issue with executing.

### ISSUE THREAD

**Issue by JFnine** [OpenSmpp/opensmpp#21]
Hi, 

correct me if I'm wrong, 

but, once I've downloaded smpp files on my server and once i've configured the smppsender.cfg file, the last thing i've to do is execute smppsender.sh? 

It does appear an error when I'm doing that: 

Error: main class not found or loaded org.smpp.client.SMPPSender

What is wrong here? 

Kind regards.

**Comment by ptomli** [comment]
It looks like there's an issue, the `smppsender.sh` script has not been updated to match the multiple-JAR format now used.

I'll try to submit a fix later but in the meantime you can fixup the `smppsender.sh` script manually, to match the JAR filenames you have downloaded/generated.

**Comment by ptomli** [comment]
Running the simulator and test client will be substantially easier once PR #29 lands
