### ISSUE TITLE
Failed to execute

### ISSUE THREAD

**Issue by iose19** [OpenSmpp/opensmpp#24]
Failed to execute goal on project opensmpp-sim: Could not resolve dependencies for project org.opensmpp:opensmpp-sim:jar:3.0.2-SNAPSHOT: Could not find artifact org.opensmpp:opensmpp-core:jar:3.0.2-SNAPSHOT -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

**Comment by ptomli** [comment]
That looks like you tried to execute maven from within the `opensmpp-sim` directory. You should execute maven from the parent

**Comment by iose19** [comment]
------------------------------------------------------------------------
Building OpenSMPP Client 3.0.2-SNAPSHOT
------------------------------------------------------------------------
The POM for org.opensmpp:opensmpp-core:jar:3.0.2-SNAPSHOT is missing, no dependency information available
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 1.001s
Finished at: Mon Jul 31 20:13:19 CEST 2017
Final Memory: 7M/135M
------------------------------------------------------------------------
Failed to execute goal on project opensmpp-client: Could not resolve dependencies for project org.opensmpp:opensmpp-client:jar:3.0.2-SNAPSHOT: Could not find artifact org.opensmpp:opensmpp-core:jar:3.0.2-SNAPSHOT -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

**Comment by iose19** [comment]
with eclipse I have this output:
Missing artifact org.opensmpp:opensmpp-core:jar:3.0.2-SNAPSHOT
