### ISSUE TITLE
Bind operation failed

### ISSUE THREAD

**Issue by iose19** [OpenSmpp/opensmpp#25]
Sorry guys but I have this issue...
Bind request (bindreq: (pdu: 0 2 0 [1]) pavel dfsew  52 (addrrang: 1 1 ) ) 
Bind operation failed. java.net.ConnectException: Connection refused: connect

I can't send any sms. Maybe I forget some configuration. Is there some doc to understand how to implement/set all parameters?
Thanks

**Comment by ptomli** [comment]
This is a normal Java exception indicating that the server you are trying to connect to is not listening on the port you are trying to connect to.

You could review the code in the simulator to get a better understanding.
