### ISSUE TITLE
java.net.ConnectException: Connection time out: connect when calling bind?

### ISSUE THREAD

**Issue by anta40** [OpenSmpp/opensmpp#34]
I tried the simulator on 2 servers: one is mine (Debian Sid), the other is my office's (Ubuntu).
On my server, the simulator runs fine. No problem so far. But on my office's, I faces an issue when choosing bind:

> 1
> Asynchronous/Synchronnous Session? (a/s) [s]
> Transmitter/Receiver/Transciever (t/r/tr) [t]
> IP address of SMSC [142.88.100.56]
> Port number [2557] 2557
> Your system ID [pavel]
> Your password [dfsew]
> Bind request (bindreq: (pdu: 0 2 0 [1]) pavel dfsew  52 (addrrang: 1 1 ) )
> Bind operation failed. java.net.ConnectException: Connection timed out: connect

What do possibly cause this connection timed out issue? Both simulators use the same config. Mine runs JDK 8, my office's runs JDK 9.

**Comment by paoloc0** [comment]
This is a network issue, it's not anything related to the software of the JVM. Try `telnet` to 142.88.100.56 port 2557 for comparison, from both locations. (Is that really the right port, I wonder ... the standard SMPP port is 2775. That one of the many possible causes. Another would be your office firewall blocking the connection.).
