### ISSUE TITLE
how to run this spmm server in local

### ISSUE THREAD

**Issue by RaviGithub555** [OpenSmpp/opensmpp#42]
Hi Team,
There is no main class available how to run the application in local?

**Comment by paoloc0** [comment]
This is an SMPP library, not an SMPP server. You can write your own server using the library, with the simulator at https://github.com/OpenSmpp/opensmpp/tree/master/sim as a starting point.

**Comment by RaviGithub555** [comment]
Hi Paoloc,
Thank you for your support, Is there any server code available on github to run smpp library.

Thanks in advanced,
Ravi kumar

**Comment by paoloc0** [comment]
Not that I know of, but you might find something if you look around. Or look at Kannel.

**Comment by RaviGithub555** [comment]
Thank you Paoloc for you support.

**Comment by RaviGithub555** [comment]
Hi Paoloc,
Sorry for that again again i am asking question, 
Like using java we can directly call simulator main class, or what should be the architecture for smpp server in java, for using smppOpen library?
Thanks & Regards,
Ravi Kumar

**Comment by paoloc0** [comment]
See my comments above. I don't think this library is what you are looking for. I suggest an off-the-shelf solution like Kannel.
