### ISSUE TITLE
guide to install

### ISSUE THREAD

**Issue by apolinux** [OpenSmpp/opensmpp#46]
I'm not familiar with java or maven, so please give me a light to start the instalation and configuration of this package.

thanks.

**Comment by ptomli** [comment]
This is not an application but rather a Java library. If you’re not familiar with programming in Java then this project isn’t going to be much use to you. 

If you want an application that interfaces with an SMPP server or client then I suggest you take a look at something like Kannel https://www.kannel.org <https://www.kannel.org/index.shtml>

**Comment by apolinux** [comment]
thanks for the answer. What I need is to enable a simple smpp server to
emulate a real server and try to interact with kannel, sending mo and mt
messages, do you know a similar package?
-
Cordialmente



*Carlos Gabriel Arce CruzSoftware Solutions Deployer*

@apolinux
Skype: carlos.gabriel.arce

**Comment by paoloc0** [comment]
Hi. I think you mean that you want a **client** to interact with an SMPP Server. Anyway: you could probably install and run Kannel, and have it talk to another Kannel (as a client).

You **can** use OpenSMPP to run a simple test, without knowing much about Java. I suspect it's not going to suit your use case, and you're probably better off with something like Kannel - but here you go, in case it's useful:

```
wget https://repo1.maven.org/maven2/org/opensmpp/opensmpp-client/3.0.0/opensmpp-client-3.0.0.jar
wget https://repo1.maven.org/maven2/org/opensmpp/opensmpp-core/3.0.0/opensmpp-core-3.0.0.jar
wget https://raw.githubusercontent.com/OpenSmpp/opensmpp/master/client/smpptest.cfg
mv smpptest.cfg smppsender.cfg
```

Now edit smppsender.cfg and configure details of the server you're connecting to, and then:

```
java -classpath opensmpp-client-3.0.0.jar:opensmpp-core-3.0.0.jar org.smpp.client.SMPPSender -dest 111111234 -message 'this is a test'
Initialising...
Reading configuration file ./smppsender.cfg...
Setting default parameters...
Sending: "this is a test" to 111111234
Bind request (bindreq: (pdu: 0 2 0 [1]) pavel dfsew Logica 52 (addrrang: 1 1 11*) )
[etc.]
```

**Comment by totadGithub1989** [comment]
Hi,
i just want to use this opensmpp jars and configuration file in my eclipse and i want to run and connect to smpp server so do i need to write one main class and run or what ?
