### ISSUE TITLE
Window Size/TPS Throttle

### ISSUE THREAD

**Issue by tkiran77** [OpenSmpp/opensmpp#48]
Hello All,
Anyone using this library is aware how to set window size or Throttle TPS based on the Server we connect to, to ensure we send not more than the configured TPS.
Any insight is really appreciated.
Regards,
Kiran

**Comment by apelzin** [comment]
I ended up writing my own code to ensure obeying TPS.

**Comment by paoloc0** [comment]
This library provides protocol-level support for SMPP, but not higher-level functionality like enforcing a window size, or even managing a window of unacknowledged PDUs - you will have to write that yourself.

**Comment by tkiran77** [comment]
Thank you for your comments. We will try to implement the same and once done we will try to see if we can share our implementation for others to use.
