### ISSUE TITLE
Will no data interaction between ESME SMSC break the binding of SMSC

### ISSUE THREAD

**Issue by xbsbsvjshs** [OpenSmpp/opensmpp#52]
Will no data interaction between ESME SMSC break the binding of SMSC.
Thank you very much!

**Comment by paoloc0** [comment]
Typically, yes. It depends on the server, and it depends on your own code, on your side - you have to implement a timer or similar, if you want it to happen from your end. Have a look at the SMPP specification for more information on timers. You may also want to look at socket timeouts, although those would typically apply over longer periods of time.
