### ISSUE TITLE
SMSC simulator

### ISSUE THREAD

**Issue by behrad** [OpenSmpp/opensmpp#8]
any docs on how to config and start the SMSC server ?!

**Comment by ptomli** [comment]
No real documentation per-se, which is a bit of a failing, but the simple way is as below

    curl -O http://central.maven.org/maven2/org/opensmpp/opensmpp-core/3.0.0/opensmpp-core-3.0.0.jar
    curl -O http://central.maven.org/maven2/org/opensmpp/opensmpp-sim/3.0.0/opensmpp-sim-3.0.0.jar
    java -cp opensmpp-core-3.0.0.jar:opensmpp-sim-3.0.0.jar org.smpp.smscsim.Simulator

**Comment by behrad** [comment]
thank you @ptomli

**Comment by behrad** [comment]
seems it needs a users file under `etc/users.txt`, how authentication should be formatted in that file?

**Comment by ptomli** [comment]
You can see an example file here
https://github.com/OpenSmpp/opensmpp/blob/master/sim/users.txt

**Comment by behrad** [comment]
thank you for your help @ptomli I'm now able to start and test SMSC however two questions came to my mind

1) I didn't receive any delivery reports, what/how should I enable them?

2) I put this under heavy load and see a low performance, any change to improve this via config? should we change the code base to a multi-threaded SMSC?

**Comment by ptomli** [comment]
The simulator is not intended to provide any real services, merely a simple tool to allow your code to connect via SMPP without having to talk to a real SMSC. If you need specific functionality for your testing then you need to implement that yourself. OpenSMPP is a library for enabling software to communicate via SMPP, it is not a complete software product, or SMSC.

**Comment by behrad** [comment]
Thank you for your time @ptomli
